# Generated by Django 5.1 on 2024-09-22 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olympic_country', models.CharField(choices=[('AF', 'Afganistán'), ('AL', 'Albania'), ('DZ', 'Argelia'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AG', 'Antigua y Barbuda'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaiyán'), ('BS', 'Bahamas'), ('BH', 'Baréin'), ('BD', 'Bangladés'), ('BB', 'Barbados'), ('BY', 'Bielorrusia'), ('BE', 'Bélgica'), ('BZ', 'Belice'), ('BJ', 'Benín'), ('BT', 'Bután'), ('BO', 'Bolivia'), ('BA', 'Bosnia y Herzegovina'), ('BW', 'Botsuana'), ('BR', 'Brasil'), ('BN', 'Brunéi'), ('BG', 'Bulgaria'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('KH', 'Camboya'), ('CM', 'Camerún'), ('CA', 'Canadá'), ('CV', 'Cabo Verde'), ('CF', 'República Centroafricana'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CO', 'Colombia'), ('KM', 'Comoras'), ('CG', 'Congo'), ('CR', 'Costa Rica'), ('HR', 'Croacia'), ('CU', 'Cuba'), ('CY', 'Chipre'), ('CZ', 'República Checa'), ('DK', 'Dinamarca'), ('DJ', 'Yibuti'), ('DM', 'Dominica'), ('DO', 'República Dominicana'), ('TL', 'Timor Oriental'), ('EC', 'Ecuador'), ('EG', 'Egipto'), ('SV', 'El Salvador'), ('GQ', 'Guinea Ecuatorial'), ('ER', 'Eritrea'), ('EE', 'Estonia'), ('ET', 'Etiopía'), ('FJ', 'Fiyi'), ('FI', 'Finlandia'), ('FR', 'Francia'), ('GA', 'Gabón'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Alemania'), ('GH', 'Ghana'), ('GR', 'Grecia'), ('GD', 'Granada'), ('GT', 'Guatemala'), ('GN', 'Guinea'), ('GW', 'Guinea-Bisáu'), ('GY', 'Guyana'), ('HT', 'Haití'), ('HN', 'Honduras'), ('HU', 'Hungría'), ('IS', 'Islandia'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Irán'), ('IQ', 'Irak'), ('IE', 'Irlanda'), ('IL', 'Israel'), ('IT', 'Italia'), ('CI', 'Costa de Marfil'), ('JM', 'Jamaica'), ('JP', 'Japón'), ('JO', 'Jordania'), ('KZ', 'Kazajistán'), ('KE', 'Kenia'), ('KI', 'Kiribati'), ('KR', 'Corea del Sur'), ('KW', 'Kuwait'), ('KG', 'Kirguistán'), ('LA', 'Laos'), ('LV', 'Letonia'), ('LB', 'Líbano'), ('LS', 'Lesoto'), ('LR', 'Liberia'), ('LY', 'Libia'), ('LI', 'Liechtenstein'), ('LT', 'Lituania'), ('LU', 'Luxemburgo'), ('MG', 'Madagascar'), ('MW', 'Malaui'), ('MY', 'Malasia'), ('MV', 'Maldivas'), ('ML', 'Malí'), ('MT', 'Malta'), ('MH', 'Islas Marshall'), ('MR', 'Mauritania'), ('MU', 'Mauricio'), ('MX', 'México'), ('FM', 'Micronesia'), ('MD', 'Moldavia'), ('MC', 'Mónaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MA', 'Marruecos'), ('MZ', 'Mozambique'), ('MM', 'Myanmar'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NL', 'Países Bajos'), ('NZ', 'Nueva Zelanda'), ('NI', 'Nicaragua'), ('NE', 'Níger'), ('NG', 'Nigeria'), ('MK', 'Macedonia del Norte'), ('NO', 'Noruega'), ('OM', 'Omán'), ('PK', 'Pakistán'), ('PW', 'Palaos'), ('PA', 'Panamá'), ('PG', 'Papúa Nueva Guinea'), ('PY', 'Paraguay'), ('PE', 'Perú'), ('PH', 'Filipinas'), ('PL', 'Polonia'), ('PT', 'Portugal'), ('QA', 'Catar'), ('RO', 'Rumania'), ('RU', 'Rusia'), ('RW', 'Ruanda'), ('KN', 'San Cristóbal y Nieves'), ('LC', 'Santa Lucía'), ('VC', 'San Vicente y las Granadinas'), ('WS', 'Samoa'), ('SM', 'San Marino'), ('ST', 'Santo Tomé y Príncipe'), ('SA', 'Arabia Saudita'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seychelles'), ('SL', 'Sierra Leona'), ('SG', 'Singapur'), ('SK', 'Eslovaquia'), ('SI', 'Eslovenia'), ('SB', 'Islas Salomón'), ('SO', 'Somalia'), ('ZA', 'Sudáfrica'), ('ES', 'España'), ('LK', 'Sri Lanka'), ('SD', 'Sudán'), ('SR', 'Surinam'), ('SZ', 'Suazilandia'), ('SE', 'Suecia'), ('CH', 'Suiza'), ('SY', 'Siria'), ('TW', 'Taiwán'), ('TJ', 'Tayikistán'), ('TZ', 'Tanzania'), ('TH', 'Tailandia'), ('TG', 'Togo'), ('TO', 'Tonga'), ('TT', 'Trinidad y Tobago'), ('TN', 'Túnez'), ('TR', 'Turquía'), ('TM', 'Turkmenistán'), ('TV', 'Tuvalu'), ('UG', 'Uganda'), ('UA', 'Ucrania'), ('AE', 'Emiratos Árabes Unidos'), ('GB', 'Reino Unido'), ('US', 'Estados Unidos'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistán'), ('VU', 'Vanuatu'), ('VE', 'Venezuela'), ('VN', 'Vietnam'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabue')], max_length=2)),
                ('discipline', models.CharField(choices=[('Gymnastics', 'Gimnasia Artística')], max_length=100)),
                ('branch', models.CharField(choices=[('Uneven Bars', 'Barras Asimétricas'), ('Balance Beam', 'Barra de Equilibrio'), ('Floor', 'Piso')], max_length=100)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AthleteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
                ('execution', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('notes', models.TextField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(limit_choices_to={'role': 'Atleta'}, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_records', to='users.profile')),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'Entrenador'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_records', to='users.profile')),
            ],
        ),
    ]
