# Generated by Django 5.1 on 2024-09-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_role_alter_athleterecord_athlete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Athlete', 'Atleta'), ('Coach', 'Entrenador')], max_length=50),
        ),
    ]
