# Generated by Django 5.1 on 2024-09-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Athlete', 'Atleta'), ('Coach', 'Coach')], default='Athlete', max_length=50),
        ),
    ]
