# Generated by Django 5.1 on 2024-09-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_security_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='security_answer',
            field=models.CharField(default='No contestada', max_length=255),
        ),
    ]
