# Generated by Django 5.1 on 2024-10-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_security_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='security_answer',
            new_name='security_answer1',
        ),
        migrations.AddField(
            model_name='profile',
            name='security_answer2',
            field=models.CharField(default='No contestada', max_length=255),
        ),
    ]
