# Generated by Django 5.1 on 2024-10-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_security_answer_profile_security_answer1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='security_answer3',
            field=models.CharField(default='No contestada', max_length=255),
        ),
    ]
