# Generated by Django 5.1 on 2024-10-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_security_answer3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='discipline',
            field=models.CharField(choices=[('Archery', 'Tiro con Arco'), ('Artistic Swimming', 'Natación Artística'), ('Athletics', 'Atletismo'), ('Badminton', 'Bádminton'), ('Basketball', 'Baloncesto'), ('Beach Volleyball', 'Voleibol de Playa'), ('Boxing', 'Boxeo'), ('Breaking', 'Breakdance'), ('Canoe Slalom', 'Piragüismo Slalom'), ('Canoe Sprint', 'Piragüismo Sprint'), ('Cycling BMX Freestyle', 'Ciclismo BMX Estilo Libre'), ('Cycling BMX Racing', 'Ciclismo BMX Carrera'), ('Cycling Mountain Bike', 'Ciclismo de Montaña'), ('Cycling Road', 'Ciclismo de Ruta'), ('Cycling Track', 'Ciclismo de Pista'), ('Diving', 'Clavados'), ('Equestrian', 'Equitación'), ('Fencing', 'Esgrima'), ('Football', 'Fútbol'), ('Golf', 'Golf'), ('Gymnastics Artistic', 'Gimnasia Artística'), ('Gymnastics Rhythmic', 'Gimnasia Rítmica'), ('Handball', 'Balonmano'), ('Hockey', 'Hockey sobre Césped'), ('Judo', 'Judo'), ('Modern Pentathlon', 'Pentatlón Moderno'), ('Rowing', 'Remo'), ('Rugby Sevens', 'Rugby a Siete'), ('Sailing', 'Vela'), ('Shooting', 'Tiro Deportivo'), ('Skateboarding', 'Skateboarding'), ('Sport Climbing', 'Escalada Deportiva'), ('Surfing', 'Surf'), ('Swimming', 'Natación'), ('Table Tennis', 'Tenis de Mesa'), ('Taekwondo', 'Taekwondo'), ('Tennis', 'Tenis'), ('Trampoline Gymnastics', 'Gimnasia de Trampolín'), ('Triathlon', 'Triatlón'), ('Volleyball', 'Voleibol'), ('Water Polo', 'Waterpolo'), ('Weightlifting', 'Halterofilia'), ('Wrestling Freestyle', 'Lucha Estilo Libre'), ('Wrestling Greco-Roman', 'Lucha Grecorromana')], max_length=100),
        ),
    ]
