# Generated by Django 5.1 on 2024-10-14 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_branch_alter_profile_discipline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='security_answer1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='security_answer2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='security_answer3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='team_name',
        ),
        migrations.CreateModel(
            name='OlympicTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olympic_country', models.CharField(choices=[('AF', 'Afganistán'), ('AL', 'Albania'), ('DZ', 'Argelia'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AG', 'Antigua y Barbuda'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaiyán'), ('BS', 'Bahamas'), ('BH', 'Baréin'), ('BD', 'Bangladés'), ('BB', 'Barbados'), ('BY', 'Bielorrusia'), ('BE', 'Bélgica'), ('BZ', 'Belice'), ('BJ', 'Benín'), ('BT', 'Bután'), ('BO', 'Bolivia'), ('BA', 'Bosnia y Herzegovina'), ('BW', 'Botsuana'), ('BR', 'Brasil'), ('BN', 'Brunéi'), ('BG', 'Bulgaria'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('KH', 'Camboya'), ('CM', 'Camerún'), ('CA', 'Canadá'), ('CV', 'Cabo Verde'), ('CF', 'República Centroafricana'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CO', 'Colombia'), ('KM', 'Comoras'), ('CG', 'Congo'), ('CR', 'Costa Rica'), ('HR', 'Croacia'), ('CU', 'Cuba'), ('CY', 'Chipre'), ('CZ', 'República Checa'), ('DK', 'Dinamarca'), ('DJ', 'Yibuti'), ('DM', 'Dominica'), ('DO', 'República Dominicana'), ('TL', 'Timor Oriental'), ('EC', 'Ecuador'), ('EG', 'Egipto'), ('SV', 'El Salvador'), ('GQ', 'Guinea Ecuatorial'), ('ER', 'Eritrea'), ('EE', 'Estonia'), ('ET', 'Etiopía'), ('FJ', 'Fiyi'), ('FI', 'Finlandia'), ('FR', 'Francia'), ('GA', 'Gabón'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Alemania'), ('GH', 'Ghana'), ('GR', 'Grecia'), ('GD', 'Granada'), ('GT', 'Guatemala'), ('GN', 'Guinea'), ('GW', 'Guinea-Bisáu'), ('GY', 'Guyana'), ('HT', 'Haití'), ('HN', 'Honduras'), ('HU', 'Hungría'), ('IS', 'Islandia'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Irán'), ('IQ', 'Irak'), ('IE', 'Irlanda'), ('IL', 'Israel'), ('IT', 'Italia'), ('CI', 'Costa de Marfil'), ('JM', 'Jamaica'), ('JP', 'Japón'), ('JO', 'Jordania'), ('KZ', 'Kazajistán'), ('KE', 'Kenia'), ('KI', 'Kiribati'), ('KR', 'Corea del Sur'), ('KW', 'Kuwait'), ('KG', 'Kirguistán'), ('LA', 'Laos'), ('LV', 'Letonia'), ('LB', 'Líbano'), ('LS', 'Lesoto'), ('LR', 'Liberia'), ('LY', 'Libia'), ('LI', 'Liechtenstein'), ('LT', 'Lituania'), ('LU', 'Luxemburgo'), ('MG', 'Madagascar'), ('MW', 'Malaui'), ('MY', 'Malasia'), ('MV', 'Maldivas'), ('ML', 'Malí'), ('MT', 'Malta'), ('MH', 'Islas Marshall'), ('MR', 'Mauritania'), ('MU', 'Mauricio'), ('MX', 'México'), ('FM', 'Micronesia'), ('MD', 'Moldavia'), ('MC', 'Mónaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MA', 'Marruecos'), ('MZ', 'Mozambique'), ('MM', 'Myanmar'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NL', 'Países Bajos'), ('NZ', 'Nueva Zelanda'), ('NI', 'Nicaragua'), ('NE', 'Níger'), ('NG', 'Nigeria'), ('MK', 'Macedonia del Norte'), ('NO', 'Noruega'), ('OM', 'Omán'), ('PK', 'Pakistán'), ('PW', 'Palaos'), ('PA', 'Panamá'), ('PG', 'Papúa Nueva Guinea'), ('PY', 'Paraguay'), ('PE', 'Perú'), ('PH', 'Filipinas'), ('PL', 'Polonia'), ('PT', 'Portugal'), ('QA', 'Catar'), ('RO', 'Rumania'), ('RU', 'Rusia'), ('RW', 'Ruanda'), ('KN', 'San Cristóbal y Nieves'), ('LC', 'Santa Lucía'), ('VC', 'San Vicente y las Granadinas'), ('WS', 'Samoa'), ('SM', 'San Marino'), ('ST', 'Santo Tomé y Príncipe'), ('SA', 'Arabia Saudita'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seychelles'), ('SL', 'Sierra Leona'), ('SG', 'Singapur'), ('SK', 'Eslovaquia'), ('SI', 'Eslovenia'), ('SB', 'Islas Salomón'), ('SO', 'Somalia'), ('ZA', 'Sudáfrica'), ('ES', 'España'), ('LK', 'Sri Lanka'), ('SD', 'Sudán'), ('SR', 'Surinam'), ('SZ', 'Suazilandia'), ('SE', 'Suecia'), ('CH', 'Suiza'), ('SY', 'Siria'), ('TW', 'Taiwán'), ('TJ', 'Tayikistán'), ('TZ', 'Tanzania'), ('TH', 'Tailandia'), ('TG', 'Togo'), ('TO', 'Tonga'), ('TT', 'Trinidad y Tobago'), ('TN', 'Túnez'), ('TR', 'Turquía'), ('TM', 'Turkmenistán'), ('TV', 'Tuvalu'), ('UG', 'Uganda'), ('UA', 'Ucrania'), ('AE', 'Emiratos Árabes Unidos'), ('GB', 'Reino Unido'), ('US', 'Estados Unidos'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistán'), ('VU', 'Vanuatu'), ('VE', 'Venezuela'), ('VN', 'Vietnam'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabue')], max_length=2)),
                ('discipline', models.CharField(choices=[('Archery', 'Tiro con Arco'), ('Artistic Swimming', 'Natación Artística'), ('Athletics', 'Atletismo'), ('Badminton', 'Bádminton'), ('Basketball', 'Baloncesto'), ('Beach Volleyball', 'Voleibol de Playa'), ('Boxing', 'Boxeo'), ('Breaking', 'Breakdance'), ('Canoe Slalom', 'Piragüismo Slalom'), ('Canoe Sprint', 'Piragüismo Sprint'), ('Cycling BMX Freestyle', 'Ciclismo BMX Estilo Libre'), ('Cycling BMX Racing', 'Ciclismo BMX Carrera'), ('Cycling Mountain Bike', 'Ciclismo de Montaña'), ('Cycling Road', 'Ciclismo de Ruta'), ('Cycling Track', 'Ciclismo de Pista'), ('Diving', 'Clavados'), ('Equestrian', 'Equitación'), ('Fencing', 'Esgrima'), ('Football', 'Fútbol'), ('Golf', 'Golf'), ('Gymnastics Artistic', 'Gimnasia Artística'), ('Gymnastics Rhythmic', 'Gimnasia Rítmica'), ('Handball', 'Balonmano'), ('Hockey', 'Hockey sobre Césped'), ('Judo', 'Judo'), ('Modern Pentathlon', 'Pentatlón Moderno'), ('Rowing', 'Remo'), ('Rugby Sevens', 'Rugby a Siete'), ('Sailing', 'Vela'), ('Shooting', 'Tiro Deportivo'), ('Skateboarding', 'Skateboarding'), ('Sport Climbing', 'Escalada Deportiva'), ('Surfing', 'Surf'), ('Swimming', 'Natación'), ('Table Tennis', 'Tenis de Mesa'), ('Taekwondo', 'Taekwondo'), ('Tennis', 'Tenis'), ('Trampoline Gymnastics', 'Gimnasia de Trampolín'), ('Triathlon', 'Triatlón'), ('Volleyball', 'Voleibol'), ('Water Polo', 'Waterpolo'), ('Weightlifting', 'Halterofilia'), ('Wrestling Freestyle', 'Lucha Estilo Libre'), ('Wrestling Greco-Roman', 'Lucha Grecorromana')], max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('olympic_country', 'discipline', 'branch')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='olympic_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='users.olympicteam'),
        ),
    ]
