# Generated by Django 5.1 on 2024-10-14 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profile_security_answer1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athletes', models.ManyToManyField(limit_choices_to={'role': 'Athlete'}, related_name='subteams_athletes', to='users.profile')),
                ('coaches', models.ManyToManyField(limit_choices_to={'role': 'Coach'}, related_name='subteams_coaches', to='users.profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subteams', to='users.olympicteam')),
            ],
        ),
    ]
