# Generated by Django 5.1 on 2024-10-19 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_name', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('athlete_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='users.athleterecord')),
            ],
        ),
    ]
