# Generated by Django 5.1 on 2024-10-19 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_evaluationcriterion_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleterecord',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='athleterecord',
            name='execution',
        ),
        migrations.RemoveField(
            model_name='athleterecord',
            name='notes',
        ),
        migrations.AlterField(
            model_name='athleterecord',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_records', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='athleterecord',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_records', to='users.profile'),
        ),
    ]
