# Generated by Django 5.1 on 2024-10-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_athleterecord_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleterecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
