BRANCH_CHOICES = {
    'Archery': [
        ('Individual Men', 'Individual Masculino'),
        ('Individual Women', 'Individual Femenino'),
        ('Team Men', 'Equipo Masculino'),
        ('Team Women', 'Equipo Femenino'),
        ('Mixed Team', 'Equipo Mixto'),
    ],
    'Artistic Swimming': [
        ('Duet', 'Dúo'),
        ('Team', 'Equipo'),
    ],
    'Athletics': [
        ('100m', '100 Metros'),
        ('200m', '200 Metros'),
        ('400m', '400 Metros'),
        ('800m', '800 Metros'),
        ('1500m', '1500 Metros'),
        ('5000m', '5000 Metros'),
        ('10,000m', '10,000 Metros'),
        ('Marathon', 'Maratón'),
        ('110m Hurdles', '110 Metros Vallas'),
        ('400m Hurdles', '400 Metros Vallas'),
        ('3000m Steeplechase', '3000 Metros Obstáculos'),
        ('4x100m Relay', 'Relevo 4x100 Metros'),
        ('4x400m Relay', 'Relevo 4x400 Metros'),
        ('20km Walk', 'Marcha 20 km'),
        ('35km Walk', 'Marcha 35 km'),
        ('High Jump', 'Salto de Altura'),
        ('Pole Vault', 'Salto con Pértiga'),
        ('Long Jump', 'Salto de Longitud'),
        ('Triple Jump', 'Triple Salto'),
        ('Shot Put', 'Lanzamiento de Peso'),
        ('Discus Throw', 'Lanzamiento de Disco'),
        ('Hammer Throw', 'Lanzamiento de Martillo'),
        ('Javelin Throw', 'Lanzamiento de Jabalina'),
        ('Decathlon', 'Decatlón (Hombres)'),
        ('Heptathlon', 'Heptatlón (Mujeres)'),
    ],
    'Badminton': [
        ('Men Singles', 'Individual Masculino'),
        ('Women Singles', 'Individual Femenino'),
        ('Men Doubles', 'Dobles Masculino'),
        ('Women Doubles', 'Dobles Femenino'),
        ('Mixed Doubles', 'Dobles Mixto'),
    ],
    'Basketball': [
        ('Men 5x5', 'Masculino 5x5'),
        ('Women 5x5', 'Femenino 5x5'),
        ('Men 3x3', 'Masculino 3x3'),
        ('Women 3x3', 'Femenino 3x3'),
    ],
    'Beach Volleyball': [
        ('Men', 'Masculino'),
        ('Women', 'Femenino'),
    ],
    'Boxing': [
        ('Flyweight Men', 'Peso Mosca Masculino'),
        ('Featherweight Men', 'Peso Pluma Masculino'),
        ('Lightweight Men', 'Peso Ligero Masculino'),
        ('Welterweight Men', 'Peso Wélter Masculino'),
        ('Middleweight Men', 'Peso Medio Masculino'),
        ('Heavyweight Men', 'Peso Pesado Masculino'),
        ('Flyweight Women', 'Peso Mosca Femenino'),
        ('Featherweight Women', 'Peso Pluma Femenino'),
        ('Lightweight Women', 'Peso Ligero Femenino'),
        ('Welterweight Women', 'Peso Wélter Femenino'),
        ('Middleweight Women', 'Peso Medio Femenino'),
    ],
    'Breaking': [
        ('Men', 'Masculino'),
        ('Women', 'Femenino'),
    ],
    'Canoe Slalom': [
        ('Kayak Men', 'Kayak Masculino'),
        ('Kayak Women', 'Kayak Femenino'),
        ('Canoe Men', 'Canoa Masculina'),
        ('Canoe Women', 'Canoa Femenina'),
    ],
    'Canoe Sprint': [
        ('Kayak Single Men', 'Kayak Individual Masculino'),
        ('Kayak Double Men', 'Kayak Doble Masculino'),
        ('Kayak Four Men', 'Kayak Cuatro Masculino'),
        ('Canoe Single Men', 'Canoa Individual Masculino'),
        ('Canoe Double Men', 'Canoa Doble Masculino'),
        ('Kayak Single Women', 'Kayak Individual Femenino'),
        ('Kayak Double Women', 'Kayak Doble Femenino'),
        ('Kayak Four Women', 'Kayak Cuatro Femenino'),
        ('Canoe Single Women', 'Canoa Individual Femenina'),
        ('Canoe Double Women', 'Canoa Doble Femenina'),
    ],
    'Cycling BMX Freestyle': [
        ('Park Men', 'Parque Masculino'),
        ('Park Women', 'Parque Femenino'),
    ],
    'Cycling BMX Racing': [
        ('Men', 'Masculino'),
        ('Women', 'Femenino'),
    ],
    'Cycling Mountain Bike': [
        ('Cross-Country Men', 'Campo a Través Masculino'),
        ('Cross-Country Women', 'Campo a Través Femenino'),
    ],
    'Cycling Road': [
        ('Road Race Men', 'Carrera de Ruta Masculina'),
        ('Road Race Women', 'Carrera de Ruta Femenina'),
        ('Time Trial Men', 'Contrarreloj Masculina'),
        ('Time Trial Women', 'Contrarreloj Femenina'),
    ],
    'Cycling Track': [
        ('Sprint Men', 'Velocidad Masculina'),
        ('Sprint Women', 'Velocidad Femenina'),
        ('Keirin Men', 'Keirin Masculino'),
        ('Keirin Women', 'Keirin Femenino'),
        ('Team Sprint Men', 'Velocidad por Equipos Masculina'),
        ('Team Sprint Women', 'Velocidad por Equipos Femenina'),
        ('Team Pursuit Men', 'Persecución por Equipos Masculina'),
        ('Team Pursuit Women', 'Persecución por Equipos Femenina'),
        ('Omnium Men', 'Omnium Masculino'),
        ('Omnium Women', 'Omnium Femenino'),
        ('Madison Men', 'Madison Masculino'),
        ('Madison Women', 'Madison Femenino'),
    ],
    'Diving': [
        ('Springboard 3m Men', 'Trampolín 3m Masculino'),
        ('Springboard 3m Women', 'Trampolín 3m Femenino'),
        ('Platform 10m Men', 'Plataforma 10m Masculino'),
        ('Platform 10m Women', 'Plataforma 10m Femenino'),
        ('Synchronized 3m Men', 'Sincronizado 3m Masculino'),
        ('Synchronized 3m Women', 'Sincronizado 3m Femenino'),
        ('Synchronized 10m Men', 'Sincronizado 10m Masculino'),
        ('Synchronized 10m Women', 'Sincronizado 10m Femenino'),
    ],
    'Equestrian': [
        ('Dressage Individual', 'Doma Individual'),
        ('Dressage Team', 'Doma por Equipos'),
        ('Eventing Individual', 'Concurso Completo Individual'),
        ('Eventing Team', 'Concurso Completo por Equipos'),
        ('Jumping Individual', 'Saltos Individual'),
        ('Jumping Team', 'Saltos por Equipos'),
    ],
    'Fencing': [
        ('Epee Men', 'Espada Masculino'),
        ('Epee Women', 'Espada Femenino'),
        ('Foil Men', 'Florete Masculino'),
        ('Foil Women', 'Florete Femenino'),
        ('Sabre Men', 'Sable Masculino'),
        ('Sabre Women', 'Sable Femenino'),
        ('Team Epee Men', 'Espada por Equipos Masculino'),
        ('Team Epee Women', 'Espada por Equipos Femenino'),
        ('Team Foil Men', 'Florete por Equipos Masculino'),
        ('Team Foil Women', 'Florete por Equipos Femenino'),
        ('Team Sabre Men', 'Sable por Equipos Masculino'),
        ('Team Sabre Women', 'Sable por Equipos Femenino'),
    ],
    'Football': [
        ('Men', 'Masculino'),
        ('Women', 'Femenino'),
    ],
    'Golf': [
        ('Individual Men', 'Individual Masculino'),
        ('Individual Women', 'Individual Femenino'),
    ],
    'Gymnastics Artistic': [
        ('Team Men', 'Equipo Masculino'),
        ('Team Women', 'Equipo Femenino'),
        ('All-Around Men', 'Individual General Masculino'),
        ('All-Around Women', 'Individual General Femenino'),
        ('Floor Exercise Men', 'Ejercicio de Suelo Masculino'),
        ('Floor Exercise Women', 'Ejercicio de Suelo Femenino'),
        ('Pommel Horse Men', 'Caballo con Arcos Masculino'),
        ('Rings Men', 'Anillas Masculino'),
        ('Vault Men', 'Salto Masculino'),
        ('Vault Women', 'Salto Femenino'),
        ('Parallel Bars Men', 'Barras Paralelas Masculino'),
        ('Horizontal Bar Men', 'Barra Fija Masculino'),
        ('Uneven Bars Women', 'Barras Asimétricas Femenino'),
        ('Balance Beam Women', 'Barra de Equilibrio Femenino'),
    ],
    'Gymnastics Rhythmic': [
        ('Individual All-Around Women', 'Individual General Femenino'),
        ('Group All-Around Women', 'Conjunto General Femenino'),
    ],
    'Handball': [
        ('Men', 'Masculino'),
        ('Women', 'Femenino'),
    ],
    'Hockey': [
        ('Men', 'Masculino'),
        ('Women', 'Femenino'),
    ],
    'Judo': [
        ('Extra Lightweight Men', 'Peso Superligero Masculino (-60 kg)'),
        ('Half Lightweight Men', 'Peso Semiligero Masculino (-66 kg)'),
        ('Lightweight Men', 'Peso Ligero Masculino (-73 kg)'),
        ('Half Middleweight Men', 'Peso Semimedio Masculino (-81 kg)'),
        ('Middleweight Men', 'Peso Medio Masculino (-90 kg)'),
        ('Half Heavyweight Men', 'Peso Semipesado Masculino (-100 kg)'),
        ('Heavyweight Men', 'Peso Pesado Masculino (+100 kg)'),
        ('Extra Lightweight Women', 'Peso Superligero Femenino (-48 kg)'),
        ('Half Lightweight Women', 'Peso Semiligero Femenino (-52 kg)'),
        ('Lightweight Women', 'Peso Ligero Femenino (-57 kg)'),
        ('Half Middleweight Women', 'Peso Semimedio Femenino (-63 kg)'),
        ('Middleweight Women', 'Peso Medio Femenino (-70 kg)'),
        ('Half Heavyweight Women', 'Peso Semipesado Femenino (-78 kg)'),
        ('Heavyweight Women', 'Peso Pesado Femenino (+78 kg)'),
        ('Mixed Team', 'Equipo Mixto'),
    ],
    'Modern Pentathlon': [
        ('Individual Men', 'Individual Masculino'),
        ('Individual Women', 'Individual Femenino'),
    ],
    'Rowing': [
        ('Single Sculls Men', 'Scull Individual Masculino'),
        ('Single Sculls Women', 'Scull Individual Femenino'),
        ('Double Sculls Men', 'Doble Scull Masculino'),
        ('Double Sculls Women', 'Doble Scull Femenino'),
        ('Quadruple Sculls Men', 'Cuádruple Scull Masculino'),
        ('Quadruple Sculls Women', 'Cuádruple Scull Femenino'),
        ('Lightweight Double Sculls Men', 'Doble Scull Ligero Masculino'),
        ('Lightweight Double Sculls Women', 'Doble Scull Ligero Femenino'),
        ('Coxless Pairs Men', 'Dos sin Timonel Masculino'),
        ('Coxless Pairs Women', 'Dos sin Timonel Femenino'),
        ('Coxless Fours Men', 'Cuatro sin Timonel Masculino'),
        ('Coxless Fours Women', 'Cuatro sin Timonel Femenino'),
        ('Eight with Coxswain Men', 'Ocho con Timonel Masculino'),
        ('Eight with Coxswain Women', 'Ocho con Timonel Femenino'),
    ],
    'Rugby Sevens': [
        ('Men', 'Masculino'),
        ('Women', 'Femenino'),
    ],
    'Sailing': [
        ('Men Dinghy One Person', 'Vela en Solitario Masculino (ILCA 7)'),
        ('Women Dinghy One Person', 'Vela en Solitario Femenino (ILCA 6)'),
        ('Skiff Men', 'Skiff Masculino (49er)'),
        ('Skiff Women', 'Skiff Femenino (49er FX)'),
        ('Mixed Multihull', 'Multicasco Mixto (Nacra 17)'),
        ('Kiteboarding Men', 'Kitesurf Masculino'),
        ('Kiteboarding Women', 'Kitesurf Femenino'),
        ('Windsurfing Men', 'Windsurf Masculino (iQFoil)'),
        ('Windsurfing Women', 'Windsurf Femenino (iQFoil)'),
    ],
    'Shooting': [
        ('10m Air Rifle Men', 'Rifle de Aire 10m Masculino'),
        ('10m Air Rifle Women', 'Rifle de Aire 10m Femenino'),
        ('50m Rifle 3 Positions Men', 'Rifle 50m 3 Posiciones Masculino'),
        ('50m Rifle 3 Positions Women', 'Rifle 50m 3 Posiciones Femenino'),
        ('10m Air Pistol Men', 'Pistola de Aire 10m Masculino'),
        ('10m Air Pistol Women', 'Pistola de Aire 10m Femenino'),
        ('25m Rapid Fire Pistol Men', 'Pistola Rápida Fuego 25m Masculino'),
        ('25m Pistol Women', 'Pistola 25m Femenino'),
        ('Trap Men', 'Foso Olímpico Masculino'),
        ('Trap Women', 'Foso Olímpico Femenino'),
        ('Skeet Men', 'Skeet Masculino'),
        ('Skeet Women', 'Skeet Femenino'),
    ],
    'Skateboarding': [
        ('Street Men', 'Calle Masculino'),
        ('Street Women', 'Calle Femenino'),
        ('Park Men', 'Parque Masculino'),
        ('Park Women', 'Parque Femenino'),
    ],
    'Sport Climbing': [
        ('Boulder Men', 'Boulder Masculino'),
        ('Boulder Women', 'Boulder Femenino'),
        ('Lead Men', 'Dificultad Masculino'),
        ('Lead Women', 'Dificultad Femenino'),
        ('Speed Men', 'Velocidad Masculino'),
        ('Speed Women', 'Velocidad Femenino'),
    ],
    'Surfing': [
        ('Men', 'Masculino'),
        ('Women', 'Femenino'),
    ],
    'Swimming': [
        ('50m Freestyle Men', '50m Libre Masculino'),
        ('50m Freestyle Women', '50m Libre Femenino'),
        ('100m Freestyle Men', '100m Libre Masculino'),
        ('100m Freestyle Women', '100m Libre Femenino'),
        ('200m Freestyle Men', '200m Libre Masculino'),
        ('200m Freestyle Women', '200m Libre Femenino'),
        ('400m Freestyle Men', '400m Libre Masculino'),
        ('400m Freestyle Women', '400m Libre Femenino'),
        ('800m Freestyle Men', '800m Libre Masculino'),
        ('800m Freestyle Women', '800m Libre Femenino'),
        ('1500m Freestyle Men', '1500m Libre Masculino'),
        ('1500m Freestyle Women', '1500m Libre Femenino'),
        ('100m Backstroke Men', '100m Espalda Masculino'),
        ('100m Backstroke Women', '100m Espalda Femenino'),
        ('200m Backstroke Men', '200m Espalda Masculino'),
        ('200m Backstroke Women', '200m Espalda Femenino'),
        ('100m Breaststroke Men', '100m Pecho Masculino'),
        ('100m Breaststroke Women', '100m Pecho Femenino'),
        ('200m Breaststroke Men', '200m Pecho Masculino'),
        ('200m Breaststroke Women', '200m Pecho Femenino'),
        ('100m Butterfly Men', '100m Mariposa Masculino'),
        ('100m Butterfly Women', '100m Mariposa Femenino'),
        ('200m Butterfly Men', '200m Mariposa Masculino'),
        ('200m Butterfly Women', '200m Mariposa Femenino'),
        ('200m Individual Medley Men', '200m Estilos Individual Masculino'),
        ('200m Individual Medley Women', '200m Estilos Individual Femenino'),
        ('400m Individual Medley Men', '400m Estilos Individual Masculino'),
        ('400m Individual Medley Women', '400m Estilos Individual Femenino'),
        ('4x100m Freestyle Relay Men', '4x100m Relevo Libre Masculino'),
        ('4x100m Freestyle Relay Women', '4x100m Relevo Libre Femenino'),
        ('4x200m Freestyle Relay Men', '4x200m Relevo Libre Masculino'),
        ('4x200m Freestyle Relay Women', '4x200m Relevo Libre Femenino'),
        ('4x100m Medley Relay Men', '4x100m Relevo Estilos Masculino'),
        ('4x100m Medley Relay Women', '4x100m Relevo Estilos Femenino'),
        ('4x100m Mixed Medley Relay', '4x100m Relevo Estilos Mixto'),
        ('4x100m Freestyle Relay Mixed', '4x100m Relevo Libre Mixto'),
    ],
    'Table Tennis': [
        ('Singles Men', 'Individual Masculino'),
        ('Singles Women', 'Individual Femenino'),
        ('Doubles Men', 'Dobles Masculino'),
        ('Doubles Women', 'Dobles Femenino'),
        ('Mixed Doubles', 'Dobles Mixto'),
        ('Team Men', 'Equipo Masculino'),
        ('Team Women', 'Equipo Femenino'),
    ],
    'Taekwondo': [
        ('Men -58kg', 'Masculino -58 kg'),
        ('Men -68kg', 'Masculino -68 kg'),
        ('Men -80kg', 'Masculino -80 kg'),
        ('Men +80kg', 'Masculino +80 kg'),
        ('Women -49kg', 'Femenino -49 kg'),
        ('Women -57kg', 'Femenino -57 kg'),
        ('Women -67kg', 'Femenino -67 kg'),
        ('Women +67kg', 'Femenino +67 kg'),
    ],
    'Tennis': [
        ('Singles Men', 'Individual Masculino'),
        ('Singles Women', 'Individual Femenino'),
        ('Doubles Men', 'Dobles Masculino'),
        ('Doubles Women', 'Dobles Femenino'),
        ('Mixed Doubles', 'Dobles Mixto'),
    ],
    'Trampoline': [
        ('Men', 'Masculino'),
        ('Women', 'Femenino'),
    ],
    'Triathlon': [
        ('Individual Men', 'Individual Masculino'),
        ('Individual Women', 'Individual Femenino'),
        ('Mixed Relay', 'Relevo Mixto'),
    ],
    'Volleyball': [
        ('Indoor Men', 'Sala Masculino'),
        ('Indoor Women', 'Sala Femenino'),
        ('Beach Men', 'Playa Masculino'),
        ('Beach Women', 'Playa Femenino'),
    ],
    'Water Polo': [
        ('Men', 'Masculino'),
        ('Women', 'Femenino'),
    ],
    'Weightlifting': [
        ('Men 61kg', 'Masculino 61 kg'),
        ('Men 73kg', 'Masculino 73 kg'),
        ('Men 89kg', 'Masculino 89 kg'),
        ('Men 102kg', 'Masculino 102 kg'),
        ('Men +102kg', 'Masculino +102 kg'),
        ('Women 49kg', 'Femenino 49 kg'),
        ('Women 59kg', 'Femenino 59 kg'),
        ('Women 71kg', 'Femenino 71 kg'),
        ('Women 81kg', 'Femenino 81 kg'),
        ('Women +81kg', 'Femenino +81 kg'),
    ],
    'Wrestling Freestyle': [
        ('Men 57kg', 'Masculino 57 kg'),
        ('Men 65kg', 'Masculino 65 kg'),
        ('Men 74kg', 'Masculino 74 kg'),
        ('Men 86kg', 'Masculino 86 kg'),
        ('Men 97kg', 'Masculino 97 kg'),
        ('Men 125kg', 'Masculino 125 kg'),
        ('Women 50kg', 'Femenino 50 kg'),
        ('Women 53kg', 'Femenino 53 kg'),
        ('Women 57kg', 'Femenino 57 kg'),
        ('Women 62kg', 'Femenino 62 kg'),
        ('Women 68kg', 'Femenino 68 kg'),
        ('Women 76kg', 'Femenino 76 kg'),
    ],
    'Wrestling Greco-Roman': [
        ('Men 60kg', 'Masculino 60 kg'),
        ('Men 67kg', 'Masculino 67 kg'),
        ('Men 77kg', 'Masculino 77 kg'),
        ('Men 87kg', 'Masculino 87 kg'),
        ('Men 97kg', 'Masculino 97 kg'),
        ('Men 130kg', 'Masculino 130 kg'),
    ],
}
